<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Ffmpeg\ffmpeg.manifest.json">
      <LogicalName>GoldsrcSoundConverter.FfmpegManifest.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
